### PR TITLE
Fix build error if INITRAMFS_IMAGE undefined

### PR DESCRIPTION
**Pull request by quic-vkraleti**
Fixed below error in linux-qcom-uki.bb when INITRAMFS_IMAGE is undefined.

ERROR: Error for linux-qcom-uki.bb:do_configure[depends], dependency '${@ '${INITRAMFS_IMAGE}:do_image_complete' if d.getVar('INITRAMFS_IMAGE') else ''}' does not contain exactly one ':' character. Task 'depends' should be specified in the form 'packagename:task'

### CODE REVIEW

**Review by lumag — CHANGES_REQUESTED** [review]
Rule of thumb "Also do this and that" => separate commits.

Also please use imperative language to describe the second commit ('remove' instead of 'removed').

**Comment by lumag** [comment]
Also could you please expand CI configuration so that such cases can be caught (please submit a PR with CI changes separately so that we can merge it first and then test this PR against the merged tree).

**Comment by quic-vkraleti** [comment]
> and CI configuration so that such cases can be caught (please submit a PR with CI changes separately so that we can merge it first and then test this

Sure, I'll update CI scripts in a separate PR and get back.

**Comment by lumag** [comment]
I don't see CI failing after the CI change in #639 .

**Comment by quic-vkraleti** [comment]
> I don't see CI failing after the CI change in #639 . Was it enough to demonstrate the issue being fixed by this PR?

To reproduce need to set INITRAMFS_IMAGE = "". Is there any configuration in CI that tests kernel without initrd?

**Comment by lumag** [comment]
> > I don't see CI failing after the CI change in #639 . Was it enough to demonstrate the issue being fixed by this PR?
> 
> To reproduce need to set INITRAMFS_IMAGE = "". Is there any configuration in CI that tests kernel without initrd?

I asked you to add necessary CI configuration.

**Comment by quic-vkraleti** [comment]
> > > I don't see CI failing after the CI change in #639 . Was it enough to demonstrate the issue being fixed by this PR?
> > 
> > 
> > To reproduce need to set INITRAMFS_IMAGE = "". Is there any configuration in CI that tests kernel without initrd?
> 
> I asked you to add necessary CI configuration.

https://github.com/Linaro/meta-qcom/pull/644 updated build template to build with & without initramfs.

**Review by lumag — CHANGES_REQUESTED** [review]
I've reviewed the error case. Please keep existing `do_configure[depends]` and provide default value (empty) for the `INITRAMFS_IMAGE`, like `kernel.bbclass` does.

**Comment by lumag** [comment]
@quic-vkraleti any chance of getting this done? I'd like to merge the fix and then backport necessary changes to the `scarthgap` branch.

**Review by lumag — APPROVED** [review]

**Pull request merged**
