### PR TITLE
README.md: added Quick build paragraph. 

### PR DESCRIPTION
**Pull request by davidinux**

### CODE REVIEW

**Comment by davidinux** [comment]
Adding quick build instructions

**Review by lumag — CHANGES_REQUESTED** [review]
Please follow the established style for the subject and commit message

**Comment by davidinux** [comment]
> Please follow the established style for the subject and commit message

Where do I find a reference guide for the subject and the commit message, please? Thanks

**Comment by lumag** [comment]
https://docs.yoctoproject.org/dev/contributor-guide/submit-changes.html#implement-and-commit-changes

But I'd say, there is a much less formal and much more useful rule: take a look around while making changes. This includes both code and commit styles.

**Pull request merged**
