### PR TITLE
scarthgap backport: qdl: update to the latest upstream

### PR DESCRIPTION
**Pull request by ricardosalveti**
Update to the latest upstream repository, which is now at https://github.com/linux-msm/qdl.git.

Relevant changes from latest upstream:
- USBDEVFS interface replaced with libusb
- Add ramdump support
- New utility 'ks' which uses sahara to load images from host to a device (relevant for Qualcomm Cloud AI 100).

Drop 0001-Makefile-Use-pkg-config-for-libxml2-detection.patch as these changes are now available upstream.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
(cherry picked from commit 51d6b308083b73d07d7d98ef9778bb9df8c99e22)

### CODE REVIEW

**Comment by ricardosalveti** [comment]
@lumag would it be ok to backport to kirkstone as well? tool just used for flashing, and it is going to be used officially by the qcom downstream bsp (which is kirkstone based).

**Comment by lumag** [comment]
@ricardosalveti yes, it's fine. Kirkstone is still alive (in theory you can even backport it to dunfell, I won't reject it).

BTW. Having a BSP on a year old LTS is ... a strange solution. If I remember correctly, it still uses 6.1 kernel, etc. And it is going to be supported until 2026, just two years  leaft (compare that to scarthgap which is going to be supported until 2028).
When the whole meta-qcom-hwe has started, we suggested to Sourabh to develop on master, so that after scarthgap gets released they can switch on the fresh LTS branch. Scarthgap was released on time, in April. So my strong recommendation remains: drop kirkstone and switch to scarthgap.

**Review by lumag — APPROVED** [review]

**Comment by lumag** [comment]
Heh, even worse. Kirkstone is two years old and is stuck with 5.15.

**Comment by ricardosalveti** [comment]
> @ricardosalveti yes, it's fine. Kirkstone is still alive (in theory you can even backport it to dunfell, I won't reject it).

Cool, will do a similar one for kirkstone then.

> BTW. Having a BSP on a year old LTS is ... a strange solution. If I remember correctly, it still uses 6.1 kernel, etc. And it is going to be supported until 2026, just two years leaft (compare that to scarthgap which is going to be supported until 2028). When the whole meta-qcom-hwe has started, we suggested to Sourabh to develop on master, so that after scarthgap gets released they can switch to the fresh LTS branch. Scarthgap was released on time, in April. So my strong recommendation remains: drop kirkstone and switch to scarthgap.

I hear you, having similar conversations internally as well.

**Comment by lumag** [comment]
My major point the support time. 2 years is nothing from the industry point of view.

**Pull request merged**
