### PR TITLE
Add qbootctl package

### PR DESCRIPTION
**Pull request by superna9999**
Add qbootclt package to control the boot A/B slot flags.

### CODE REVIEW

**Comment by superna9999** [comment]
If we flash the bootimage on recent platform with A/B enabled, if the boot isn't marked successful for N times, the boot will fail until `fastboot set_active a` is called, which can be unconvenient,

**Comment by lumag** [comment]
Could you please add a `.service`, calling `qbootctl` to mark it as successful?

**Comment by superna9999** [comment]
Yep it was my next plan, but I'm unsure what would be the condition, the grub one doesn't see very good since it requires a login (https://github.com/rhboot/grub2/blob/7de33f4072abf5f14c4fdad6e566c58bdbf3b26e/docs/grub-boot-success.timer)

**Comment by superna9999** [comment]
OK i"ll use the same as the systemd one https://github.com/endlessm/systemd/blob/master/units/systemd-bless-boot.service.in

**Comment by lumag** [comment]
`boot-complete.target` looks good.

**Comment by superna9999** [comment]
Done

**Comment by superna9999** [comment]
Updated recipe to 0.1.2 release since master has some bugs

**Comment by lumag** [comment]
@superna9999 I tried enabling qbootctl, and it fails:
```
| ../git/qbootctl.cpp: In function 'int get_slot_info(slot_info*)':
| ../git/qbootctl.cpp:105:9: error: 'uint32_t' was not declared in this scope
|   105 |         uint32_t active_slot = impl->getActiveBootSlot();
|       |         ^~~~~~~~
| ../git/qbootctl.cpp:30:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
|    29 | #include "bootctrl.h"
|   +++ |+#include <cstdint>
|    30 |
| ../git/qbootctl.cpp:107:15: error: 'active_slot' was not declared in this scope
|   107 |         slots[active_slot].active = true;
|       |               ^~~~~~~~~~~

**Comment by superna9999** [comment]
Indeed, it requires https://gitlab.com/sdm845-mainline/qbootctl/-/commit/df63d7c21c19a3e3afb41d029b97b9d068880484 for GCC13, adding it to the recipe.

**Comment by superna9999** [comment]
Done, added the right fix

**Comment by lumag** [comment]
Validated and merged

**Pull request merged**
